version: "3.4"

services:
  tokenauth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tokenauth
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT
      - SECRET_KEY
    ports:
      - 8080:8080
